### ISSUE TITLE
Error: User Service

### ISSUE THREAD

**Issue by hiMinju** [Yaneodoo/bistroad-user-service#1]
![image](https://user-images.githubusercontent.com/37239344/93363286-ff8b2480-f881-11ea-88b4-a29479482cc6.png)
위의 사진과 같이 오류가 나는데 혹시 이유를 아실까요?

**Comment by woodyn1002** [comment]
Gateway의 CORS 관련 설정이 누락됐던 것 같습니다. 수정했으니 확인 부탁드립니다.
이슈 감사합니다!
